version: '3.7'
services:
  server:
    image: >-
      bropat/eufy-security-ws@sha256:d41169205f4e20e1e7e173283aaf8bb2d68e2abecb42bc1500a5fac5bb7a8750
    container_name: eufy-security-ws
    restart: always
    network_mode: host
    env_file:
      - ${APP_DATA_DIR}/eufy.env
    volumes:
      - ${APP_DATA_DIR}/data:/data
