services:
  app_proxy:
    environment:
      APP_HOST: homelab-glances_web_1
      APP_PORT: 61208
      PROXY_AUTH_ADD: 'false'
    container_name: homelab-glances_app_proxy_1
  web:
    image: nicolargo/glances:4.5.6-full
    environment:
      - TZ=Europe/Berlin
      - GLANCES_OPT=-w
    pid: host
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    container_name: homelab-glances_web_1
