services:
  app_proxy:
    environment:
      APP_HOST: pingvin
      APP_PORT: 3000
      PROXY_AUTH_ADD: 'false'
      PROXY_TRUST_UPSTREAM: 'true'
    container_name: homelab-pingvin_app_proxy_1
    depends_on:
      - pingvin
  pingvin:
    image: stonith404/pingvin-share:latest
    container_name: pingvin
    restart: always
    ports:
      - '3010:3000'
    volumes:
      - ${APP_DATA_DIR}/data:/opt/app/backend/data
      - ${APP_DATA_DIR}/data/images:/opt/app/frontend/public/img
    environment:
      - TRUST_PROXY=true
      - URL=https://download.steffen-spielmann.de
