services:
  app_proxy:
    environment:
      APP_HOST: jelly_sparkle_hub_web_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  web:
    container_name: jelly_sparkle_hub_web_1
    build: ${APP_DATA_DIR}
    image: local/jelly-sparkle-hub:1.0.0
    restart: unless-stopped
