services:
  app_proxy:
    container_name: jelly-sparkle-hub_app_proxy_1
    environment:
      APP_HOST: jelly_sparkle_hub_web_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  web:
    container_name: jelly_sparkle_hub_web_1
    image: ghcr.io/steffen1413/jelly-sparkle-hub@sha256:e7a11e43e142934c94def500cd94c3b03aec2a7d54ab1c34cc7a8297a2a7941f
    restart: unless-stopped
    env_file:
      - ${APP_DATA_DIR}/.env.runtime
