services:
  app_proxy:
    container_name: jelly-sparkle-hub_app_proxy_1
    environment:
      APP_HOST: jelly_sparkle_hub_web_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  web:
    container_name: jelly_sparkle_hub_web_1
    image: ghcr.io/steffen1413/jelly-sparkle-hub@sha256:4857a637442fcfcac2c2a19704ea131acf51c87a3a2dd87da5d9f18f81e4828b
    restart: unless-stopped
    env_file:
      - ${APP_DATA_DIR}/.env.runtime
