services:
  app_proxy:
    container_name: jelly-sparkle-hub_app_proxy_1
    environment:
      APP_HOST: jelly_sparkle_hub_web_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  web:
    container_name: jelly_sparkle_hub_web_1
    image: ghcr.io/steffen1413/jelly-sparkle-hub@sha256:4062c7b9e888e47848e0958d81a662097b48bb6b10ba2fd027ecc171f4feafd3
    restart: unless-stopped
    env_file:
      - ${APP_DATA_DIR}/.env.runtime
