services:
  app_proxy:
    environment:
      APP_HOST: jellystat
      APP_PORT: 3000
      PROXY_AUTH_ADD: 'false'
    container_name: homelab-jellystat_app_proxy_1
    depends_on:
      - jellystat
  postgres:
    image: postgres:15
    container_name: jellystat-db
    restart: always
    environment:
      POSTGRES_USER: jellystat
      POSTGRES_PASSWORD: jellystatpass
      POSTGRES_DB: jellystat
    volumes:
      - ${APP_DATA_DIR}/db:/var/lib/postgresql/data
  jellystat:
    image: ghcr.io/cyfershepard/jellystat:1.1.7
    container_name: jellystat
    restart: always
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: jellystat
      POSTGRES_PASSWORD: jellystatpass
      POSTGRES_DB: jellystat
      POSTGRES_IP: postgres
      POSTGRES_PORT: 5432
      JWT_SECRET: supersecretkey
    ports:
      - '3001:3000'
